---
- name: Install common development packages
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items: "{{ common_dev_pkgs }}"
  become:
    yes

- name: Install common editors
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items: "{{ common_editor_pkgs }}"
  become:
    yes

- name: Install common shells
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items: "{{ common_shell_pkgs }}"
  become:
    yes

- name: Install common troubleshooting tools
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items: "{{ common_ts_pkgs }}"
  become:
    yes